### ISSUE TITLE
Integrate this kind of pinyin search into Search commands (e.g. `isearch-forward')?

### ISSUE THREAD

**Issue by xuchunyang** [redguardtoo/find-by-pinyin-dired#4]
At least it can avoid toggling input method.

**Comment by redguardtoo** [comment]
interesting idea.

**Comment by xuchunyang** [comment]
Below is a initial implementation of this feature:

``` lisp
(defun pinyin-search-forward (pinyin)
  (interactive "sSearch Chinese forward with Pinyin: ")
  (let ((regexp ""))
    (mapc
     (lambda (ch) (setq regexp (concat regexp (nth (- ch ?a) fbpd-char-table))))
     pinyin)
    (call-interactively 'isearch-forward-regexp)
    (setq isearch-yank-flag t)
    (isearch-process-search-string regexp "")))
```

Of course, it doesn't work like isearch which can search as you type, and I'm digging slowly into `isearch.el` to try to figure out how to improve this. If you have any suggestion or tip, please let me know.

Anyway, thank you for sharing this package. I'm closing this issue since this feature is not directly related to your package.

**Comment by xuchunyang** [comment]
This feature is now implemented in [pinyin-search.el](https://github.com/xuchunyang/pinyin-search.el)  package and available on Melpa.
